# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.

[tool.coverage.run]
branch = true

[tool.coverage.report]
show_missing = true

[tool.pytest.ini_options]
minversion = "6.0"
log_cli_level = "INFO"

[tool.ruff]
line-length = 99
include = ["pyproject.toml", "src/**/*.py", "tests/**/*.py"]
extend-exclude = ["__pycache__", "*.egg_info"]
target-version = "py312"

[tool.ruff.lint]
select = ["E", "W", "F", "C", "N", "D"]
ignore = [
    "D100",
    "D101", 
    "D102",
    "D103",
    "D105",
    "D107",
    "D203",
    "D204",
    "D213",
    "D215",
    "D400",
    "D404",
    "D406",
    "D407",
    "D408",
    "D409",
    "D413",
    "E501",
]
per-file-ignores = {"tests/*" = ["D100","D101","D102","D103","D104"]}

[tool.ruff.lint.pydocstyle]
convention = "google"
